"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.areas = void 0;
exports.areas = [
    {
        code: "FC",
        name: "Abuja",
        lgas: ["Abuja", "Kwali", "Kuje", "Gwagwalada", "Bwari", "Abaji"],
        subs: {
            Abuja: [
                "Asokoro",
                "Central Business District",
                "Garki",
                "Gwarinpa",
                "Jabi",
                "Karimu",
                "Kubwa",
                "Maitama",
                "Nyanya",
                "Wuse 1",
                "Wuse 2",
            ],
            Kwali: ["Kwali", "Bako", "Gwako", "Pasali"],
            Kuje: ["Kuje", "Gwagwalada-Kwali", "Pegi", "Yangoji"],
            Gwagwalada: ["Gwagwalada", "Dobi", "Kwali", "Kwali Rural", "Tunga-Maje"],
            Bwari: [
                "Bwari",
                "Byazhin",
                "Dutse",
                "Kubwa 2",
                "Kuchigoro",
                "Pape",
                "Saburi",
                "Shere",
                "Suru",
                "Ushafa",
                "Usman",
                "Zuba",
            ],
            Abaji: ["Abaji", "Kwaba", "Mamusa", "Pasali", "Rimu", "Yaba"],
        },
    },
    {
        code: "AB",
        name: "Abia",
        lgas: [
            "Aba North",
            "Aba South",
            "Arochukwu",
            "Bende",
            "Ikawuno",
            "Ikwuano",
            "Isiala-Ngwa North",
            "Isiala-Ngwa South",
            "Isuikwuato",
            "Umu Nneochi",
            "Obi Ngwa",
            "Obioma Ngwa",
            "Ohafia",
            "Ohaozara",
            "Osisioma",
            "Ugwunagbo",
            "Ukwa West",
            "Ukwa East",
            "Umuahia North",
            "Umuahia South",
        ],
        subs: {
            "Aba North": [
                "Aba Central",
                "Aba Station",
                "Aba-Ukwu",
                "Eziukwu",
                "Asaokpu",
                "St. Eugene",
                "Ogbor Hill",
                "Umuola",
                "Ntighauzo",
                "Umuogele",
            ],
            "Aba South": [
                "Ariaria",
                "Cemetery",
                "Ehere",
                "Eziama",
                "Obohia",
                "Ohazu",
                "Oguduasaa",
                "Ohanze",
                "Uratta",
                "Umule",
            ],
            Arochukwu: [
                "Amasu",
                "Asaga",
                "Atani",
                "Azumini",
                "Bende",
                "Isu",
                "Ohafia",
                "Obinkita",
                "Okagwe",
                "Ututu",
            ],
            Bende: [
                "Amaukwu",
                "Amaogudu",
                "Amavo",
                "Amede",
                "Amokwe",
                "Asaga",
                "Azumini",
                "Eziukwu",
                "Ibenda",
                "Ikwukwu",
                "Ikwunga",
                "Ile",
                "Isiala",
                "Item",
                "Obikabia",
                "Obohia",
                "Ogboji",
                "Ohafia",
                "Okon-Aku",
                "Ugwueke",
                "Umuhu Ezechi",
                "Umu-Imenyi",
                "Umunna",
                "Uturu",
                "Uzuakoli",
            ],
            Ikawuno: [
                "Akawa",
                "Amaise",
                "Amokwu",
                "Anaba",
                "Aro-Ngwa",
                "Asaa",
                "Dibeji",
                "Eziama",
                "Isingwu",
                "Mgboko",
                "Oloko",
                "Omeiheukwu",
                "Ugwuabia",
                "Ugwueme",
                "Umu-ahia",
                "Umuakwu",
                "Umuobasi",
                "Umuosu",
                "Umunneato",
                "Umuru",
            ],
            Ikwuano: [
                "Abayi",
                "Aboh",
                "Ahiaba",
                "Amaise",
                "Asaga",
                "Ebem",
                "Eziama",
                "Ibeku",
                "Ikwuano",
                "Isuikwuato",
                "Mbawsi",
                "Mgboko",
                "Okafia",
                "Okaiuga",
                "Okon-Aku",
                "Okwe",
                "Olokoro",
                "Ubaha",
                "Umuelem",
                "Umuene",
                "Umuikaa",
            ],
            "Isiala-Ngwa North": [
                "Amaiyi",
                "Amoba",
                "Mgboko",
                "Mgboko Umuola",
                "Nenu",
                "Obikabia",
                "Okpuala Ngwa",
                "Okpu Umuobo",
                "Okwuta",
                "Ovom",
                "Umuagbai",
                "Umuagwo",
                "Umuchime",
                "Umudike",
                "Umuezeala",
                "Umuikea",
                "Umuma Isingwu",
                "Umunneato",
                "Umuokpo",
                "Umuosu",
                "Umuowa",
                "Umuozuo",
                "Uratta",
                "Ururuka",
            ],
            "Isiala-Ngwa South": [
                "Ahiaba",
                "Arochukwu Road",
                "Asaga",
                "Asaokpu",
                "Asato",
                "Dikeoha",
                "Egbelu",
                "Ehume",
                "Ekwereazu",
                "Ekwueme",
                "Elu",
                "Isingwu",
                "Ndiolumbe",
                "Ntighauzo",
                "Ofeke",
                "Ogbor Hill",
                "Okpuala",
                "Umualumaku",
                "Umualumoke",
                "Umuawa Alaocha",
                "Umuawa Uka",
                "Umuawulu",
                "Umuehim Nvosi",
                "Umule",
            ],
            Isuikwuato: [
                "Amaokwe",
                "Amuma",
                "Amuzukwu",
                "Ibeku Olokoro",
                "Isiala",
                "Isuamawu",
                "Ndi Oji Abam",
                "Nenu Okpanku",
                "Nkwoegwu",
                "Ntigha",
                "Olokoro",
                "Omoba",
                "Ovum",
                "Ubaekwem",
                "Ubakala",
                "Ugwuati",
                "Umuchiukwu",
                "Umunneochi",
                "Umuokpo",
                "Umuoriehi",
                "Umuosu",
                "Umuru",
                "Umusedi",
                "Uturu",
            ],
            "Umu Nneochi": [
                "Amato",
                "Asaga",
                "Ebem",
                "Ibeku",
                "Igbeagu",
                "Isuochi",
                "Item",
                "Nneato",
                "Okaiuga Alaike",
                "Okaiuga Nkwoegwu",
                "Umukabia",
            ],
            "Obi Ngwa": [
                "Amaise",
                "Amaokwe",
                "Eziama",
                "Isiala Obi",
                "Obi Ngwa",
                "Ohiya",
                "Owaza",
                "Umuneochi",
                "Umuokpo",
                "Umuokwara",
            ],
            "Obioma Ngwa": [
                "Ahiaba",
                "Amaogudu",
                "Aro-Ngwa",
                "Eziama",
                "Ibeku",
                "Isiala Obioma",
                "Isi-Ala Ngwa",
                "Ndume",
                "Nenu",
                "Obohia",
                "Obukwu",
                "Umuokoro",
            ],
            Ohafia: [
                "Amaekpu",
                "Arochukwu",
                "Asaga",
                "Bende",
                "Elu",
                "Isu",
                "Item",
                "Ivo",
                "Nkporo",
                "Ohafia",
                "Okagwe",
                "Okon-Aku",
                "Umukabia",
            ],
            Ohaozara: [
                "Agbaja",
                "Amazu",
                "Edda",
                "Ezaa",
                "Izzi",
                "Nkwegu",
                "Obiozara",
                "Okposi",
            ],
            Osisioma: [
                "Amaise",
                "Amavo",
                "Isiala Ngwa",
                "Ndume",
                "Nenu",
                "Obioma Ngwa",
                "Ogbor Hill",
                "Ohiya",
                "Okpu-Umuobo",
                "Ossah",
                "Ubakala",
                "Ugwunagbo",
            ],
            Ugwunagbo: [
                "Amaokwe",
                "Arochukwu",
                "Asaga",
                "Atani",
                "Azu Ogbunike",
                "Bende",
                "Eziama",
                "Mgbaja",
                "Nkwo Mgbaja",
                "Owaza",
                "Umukabia",
            ],
            "Ukwa West": [
                "Ekpiri Nnanabo",
                "Elile",
                "Kwakwara",
                "Nto Edino",
                "Okafia",
                "Okeikpe",
                "Okoko Item",
                "Omuma",
                "Umu Nwankwo",
                "Umuaku",
                "Umuebulu",
                "Umuikea",
                "Umuola",
                "Uturu",
            ],
            "Ukwa East": [
                "Abayi",
                "Akpaa",
                "Akuma",
                "Ekere Nta",
                "Eziama",
                "Okpuje",
                "Ugwueke",
            ],
            "Umuahia North": [
                "Amafor",
                "Amuzukwu",
                "Atta",
                "Ibeku",
                "Isingwu",
                "Ndume",
                "Umuakpara",
                "Umuokpara",
                "Umualor",
                "Umuawa",
                "Ubakala",
            ],
            "Umuahia South": [
                "Amaise",
                "Amaiyi",
                "Arochukwu",
                "Asata",
                "Ehimiri",
                "Ihie",
                "Mbutu",
                "Nenu",
                "Nkata",
                "Okwuta",
                "Olokoro",
                "Ubani",
                "Umuene",
                "Umuobasi",
                "Umule",
            ],
        },
    },
    {
        code: "AD",
        name: "Adamawa",
        lgas: [
            "Demsa",
            "Fufore",
            "Ganye",
            "Girei",
            "Gombi",
            "Guyuk",
            "Hong",
            "Jada",
            "Lamurde",
            "Madagali",
            "Maiha",
            "Mayo-Belwa",
            "Michika",
            "Mubi-North",
            "Mubi-South",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola North",
            "Yola South",
        ],
        subs: {
            Demsa: ["Demsa", "Kiri", "Numan", "Sina"],
            Fufore: [
                "Bali",
                "Belel",
                "Damsa",
                "Fufore",
                "Garta",
                "Gurin",
                "Jada",
                "Kafin Hausa",
                "Kurmi",
                "Kwaja",
                "Luggere",
                "Mbori",
                "Miyanga",
                "Njoboli",
                "Siri",
                "Yashi",
            ],
            Ganye: [
                "Ganye",
                "Jada",
                "Kafin Hausa",
                "Kurmi",
                "Kwaja",
                "Luggere",
                "Mbori",
                "Miyanga",
                "Njoboli",
                "Siri",
                "Yashi",
            ],
            Girei: ["Girei", "Kurmi", "Luggere", "Maya", "Nguroje", "Savannah"],
            Gombi: [
                "Dilchim",
                "Gadaka",
                "Gombi",
                "Kwamti",
                "Pella",
                "Tashan",
                "Wuro-Bokki",
            ],
            Guyuk: [
                "Boshikiri",
                "Gombi",
                "Guyuk",
                "Jengre",
                "Kiri",
                "Kwada",
                "Toungo",
            ],
            Hong: [
                "Girei",
                "Hong",
                "Jada",
                "Kafin Hausa",
                "Kurmi",
                "Kwaja",
                "Luggere",
                "Mbori",
                "Miyanga",
                "Njoboli",
                "Siri",
                "Yashi",
            ],
            Jada: [
                "Ganye",
                "Jada",
                "Kafin Hausa",
                "Kurmi",
                "Kwaja",
                "Luggere",
                "Mbori",
                "Miyanga",
                "Njoboli",
                "Siri",
                "Yashi",
            ],
            Lamurde: [
                "Bashinde",
                "Dit",
                "Gwako",
                "Jalingo-Maiha",
                "Lamurde",
                "Lau",
                "Shelleng",
                "Sukur",
            ],
            Madagali: ["Duhu", "Gulak", "Kirchinga", "Kuda", "Madagali", "Shuwa"],
            Maiha: [
                "Gella",
                "Jalingo-Maiha",
                "Kala'a",
                "Kwajaffa",
                "Maiha",
                "Mbuta",
                "Muduvu",
                "Sina",
                "Sulaimanti",
                "Tal",
                "Wuro-Gandi",
            ],
            "Mayo-Belwa": [
                "Babare",
                "Bashinde",
                "Dit",
                "Gwako",
                "Jalingo-Maiha",
                "Lamurde",
                "Lau",
                "Shelleng",
                "Sukur",
            ],
            Michika: [
                "Garta",
                "Kirchinga",
                "Kuda",
                "Madagali",
                "Makwada",
                "Michika",
                "Pella",
            ],
            "Mubi-North": [
                "Garta",
                "Karewa",
                "Kirkuk",
                "Kofare",
                "Kwaja",
                "Legire",
                "Mararaba",
                "Mayo-Belwa",
                "Mbulo",
                "Mubi-North",
                "Mubi-South",
                "Njoboli",
                "Shani",
                "Sukur",
                "Vintim",
                "Watu",
            ],
            "Mubi-South": [
                "Bazza",
                "Bazza",
                "Gella",
                "Gude",
                "Jalingo-Maiha",
                "Kala'a",
                "Kwajaffa",
                "Lamurde",
                "Maiha",
                "Mbuta",
                "Muduvu",
                "Sina",
                "Sulaimanti",
                "Tal",
                "Wuro-Gandi",
            ],
            Numan: [
                "Dikong",
                "Guyuk",
                "Kiri",
                "Lamurde",
                "Numan",
                "Pella",
                "Savannah",
            ],
            Shelleng: [
                "Babare",
                "Bashinde",
                "Dit",
                "Gwako",
                "Jalingo-Maiha",
                "Lamurde",
                "Lau",
                "Shelleng",
                "Sukur",
            ],
            Song: ["Gombi", "Guyuk", "Jengre", "Kiri", "Kwada", "Toungo"],
            Toungo: ["Gombi", "Guyuk", "Jengre", "Kiri", "Kwada", "Toungo"],
            "Yola North": [
                "Gwadabawa",
                "Jambutu",
                "Jimeta",
                "Karewa",
                "Kofare",
                "Kwajaffa",
                "Legire",
                "Mararaba",
                "Mayo-Belwa",
                "Mbulo",
                "Mubi-North",
                "Mubi-South",
                "Njoboli",
                "Shani",
                "Sukur",
                "Vintim",
                "Wat",
            ],
            "Yola South": [
                "Gwadabawa",
                "Jambutu",
                "Jimeta",
                "Karewa",
                "Kofare",
                "Kwajaffa",
                "Legire",
                "Mararaba",
                "Mayo-Belwa",
                "Mbulo",
                "Mubi-North",
                "Mubi-South",
                "Njoboli",
                "Shani",
                "Sukur",
                "Vintim",
                "Wat",
            ],
        },
    },
    {
        code: "AK",
        name: "AkwaIbom",
        lgas: [
            "Abak",
            "Eastern-Obolo",
            "Eket",
            "Esit-Eket",
            "Essien-Udim",
            "Etim-Ekpo",
            "Etinan",
            "Ibeno",
            "Ibesikpo-Asutan",
            "Ibiono-Ibom",
            "Ika",
            "Ikono",
            "Ikot-Abasi",
            "Ikot-Ekpene",
            "Ini",
            "Itu",
            "Mbo",
            "Mkpat-Enin",
            "Nsit-Atai",
            "Nsit-Ibom",
            "Nsit-Ubium",
            "Obot-Akara",
            "Okobo",
            "Onna",
            "Oron",
            "Oruk Anam",
            "Udung-Uko",
            "Ukanafun",
            "Urue-Offong/Oruko",
            "Uruan",
            "Uyo",
        ],
        subs: {
            Abak: ["Abak Atama", "Abak Urban", "Afa-Uda"],
            "Eastern-Obolo": [
                "Akpanya",
                "Atibe",
                "Ebughu",
                "Ekede",
                "Ikot Akani",
                "Ikot Akpan Udo",
                "Ikot Udoe",
                "Mbak Atai",
                "Mkpanak",
                "Nduo Eduo",
                "Nduo Eyo",
                "Nduo Nta",
                "Nkana",
                "Nkot Abasi",
                "Obotme",
                "Ukwok",
                "Uya Oro",
            ],
            Eket: [
                "Afaha Eket",
                "Eket",
                "Ekong Nta",
                "Iko",
                "Ikot Akpan Abia",
                "Ikot Akpan Afaha",
                "Ikot Akpan Etefia",
                "Ikot Akpan Nkuk",
                "Ikot Akpan Udo",
                "Ikot Ayan",
                "Ikot Edibong",
                "Ikot Emem",
                "Ikot Ekang",
                "Ikot Etobo",
                "Ikot Ibiok",
                "Ikot Idem",
                "Ikot Inyang",
                "Ikot Mfon",
                "Ikot Obong",
                "Ikot Udota",
                "Ikot Uso Akpan",
                "Nduo Eduo",
            ],
            "Esit-Eket": [
                "Edem Idim",
                "Eket-Oron Road",
                "Esit-Eket Urban",
                "Ikot Abasi Akpan",
                "Ikot Akpan Abia",
                "Ikot Akpan Ishiet",
                "Ikot Akpan Nkuk",
                "Ikot Akpan Udo",
                "Ikot Ansa",
                "Ikot Asang",
                "Ikot Ebiere",
                "Ikot Ekang",
                "Ikot Ekpene",
                "Ikot Esenam",
                "Ikot Etobo",
                "Ikot Ibiok",
                "Ikot Ibritam",
                "Ikot Idem",
                "Ikot Inyang",
                "Ikot Mfon",
                "Ikot Obong",
                "Ikot Udo Offiong",
                "Ikot Usen",
                "Inua Eyet Ikot",
            ],
            "Essien-Udim": [
                "Afaha Offiong",
                "Afaha Ubium",
                "Awa",
                "Edem Idim Okpot",
                "Ediene Abak",
                "Ekpat Nsit",
                "Ikot Abasi",
                "Ikot Akan",
                "Ikot Edeghe",
                "Ikot Udo Essang",
                "Ikwuano",
                "Ini",
                "Ndiya",
                "Nto Edino",
                "Obotme",
                "Okon",
                "Okoroete",
                "Udoudom",
            ],
            "Etim-Ekpo": [
                "Arochukwu",
                "Ekpo Atai",
                "Etim Ekpo",
                "Ibiaku Ntok Okpo",
                "Ikot Akpa Nkuk",
                "Ikot Edeh",
                "Ikot Essien",
                "Ikot Inyang",
                "Ikot Ndon",
                "Ikot Obio Atai",
                "Ikot Okoro",
                "Ndon Eyo",
                "Nto Nsek",
            ],
            Etinan: [
                "Atan Offot",
                "Eka Uruk Eshiet",
                "Etebi",
                "Etinan Central",
                "Ikot Abia",
                "Ikot Akpan Abia",
                "Ikot Akpan Afaha",
                "Ikot Akpan Essien",
                "Ikot Akpawat",
                "Ikot Ebiere",
                "Ikot Etim",
                "Ikot Ini",
                "Ikot Nkan",
                "Ikot Obong",
                "Ikot Udo Nseyo",
                "Ikot Uso Akpan",
                "Urua Atai Ibiaku",
                "Urua Inyang",
                "Urua Nteghe",
                "Urua Offong Oruko",
                "Urua Ubon",
            ],
            Ibeno: [
                "Atabrikang",
                "Eket Offiong",
                "Eket Uqua",
                "Esuk Mba",
                "Ibeno",
                "Iko",
                "Ikot Abasi",
                "Ikot Akpan Afaha",
                "Ikot Akpan Eda",
                "Ikot Akpan Essien",
                "Ikot Ayan Itam",
                "Ikot Edem Udo",
                "Ikot Ekang",
                "Ikot Etefia",
                "Ikot Ibiok",
                "Ikot Ita",
                "Ikot Itina",
                "Ikot Ntuk",
                "Ikot Obot",
                "Ikot Udobong",
                "Ikot Udoma",
                "Inua Eyet Ikot",
                "Odio",
                "Usuk Eto Ekong",
            ],
            "Ibesikpo-Asutan": [
                "Afaha Offiong",
                "Afaha Ubium",
                "Awa",
                "Edem Idim Okpot",
                "Ediene Abak",
                "Ekpat Nsit",
                "Ikot Abasi",
                "Ikot Akan",
                "Ikot Edeghe",
                "Ikot Udo Essang",
                "Ikwuano",
                "Ini",
                "Ndiya",
                "Nto Edino",
                "Obotme",
                "Okon",
                "Okoroete",
                "Udoudom",
            ],
            "Ibiono-Ibom": [
                "Asuna",
                "Etebi",
                "Ikot Edor",
                "Ikot Ekpene Obo",
                "Ikot Essien",
                "Ikot Inyang",
                "Ikot Nsek",
                "Ikot Okoro",
                "Mbente",
                "Nto Udo",
                "Okon",
                "Okoroete",
                "Ukpom",
                "Urua Inyang",
                "Urua Okpo",
                "Urua Ossom",
            ],
            Ika: [
                "Arochukwu",
                "Ekpo Atai",
                "Etim Ekpo",
                "Ibiaku Ntok Okpo",
                "Ikot Akpa Nkuk",
                "Ikot Edeh",
                "Ikot Essien",
                "Ikot Inyang",
                "Ikot Ndon",
                "Ikot Obio Atai",
                "Ikot Okoro",
                "Ndon Eyo",
                "Nto Nsek",
            ],
            Ikono: [
                "Awa",
                "Etebi",
                "Ikot Afaha",
                "Ikot Edehe",
                "Ikot Emem",
                "Ikot Etefia",
                "Ikot Idem",
                "Ikot Inyang",
                "Ikot Nseyen",
                "Ikot Oku Usung",
                "Ikot Udo Ete",
                "Ikot Udom",
                "Ikot Ukpong",
                "Ikot Uso Akpan",
                "Ndiya Usung Inyang",
                "Nnung Ikot",
                "Okon Eket",
                "Okon Eket Ii",
                "Okon Eket Iii",
                "Uruk Atta 11",
                "Uruk Atta I",
                "Uruk Atta Ii",
                "Uruk Uso",
            ],
            "Ikot-Abasi": [
                "Arochukwu",
                "Atan",
                "Edem Idim",
                "Ekparakwa",
                "Enwang",
                "Ete",
                "Ikot Abasi",
                "Ikot Ada Akpan",
                "Ikot Akpaden",
                "Ikot Antem",
                "Ikot Edibon",
                "Ikot Essien",
                "Ikot Ibritam",
                "Ikot Ifie",
                "Ikot Imo",
                "Ikot Isong",
                "Ikot Ntuen",
                "Ikot Okoro",
                "Ikot Udo",
                "Ikot Udoma",
                "Manta",
                "Mbak Atai",
                "Ndiya",
                "Nung Udoe",
                "Ogboinim",
                "Okon",
                "Osiok",
                "Ukpom",
            ],
            "Ikot-Ekpene": [
                "Awa",
                "Eka",
                "Ikot Akpabio",
                "Ikot Edeh",
                "Ikot Ekpene Urban I",
                "Ikot Ekpene Urban Ii",
                "Ikot Etiebet",
                "Ikot Inyang",
                "Ikot Udoma",
                "Ikot Udo Obobo",
                "Ikot Udom",
                "Ikot Umoessien",
                "Ikot Unya",
                "Ikpom",
                "Inen",
                "Nto Nsek",
                "Ogweho",
                "Okon Eket",
                "Okon Inyang",
                "Ukpom Abak",
            ],
            Ini: [
                "Afaha Ube",
                "Efa",
                "Ikot-Akan",
                "Ikot-Edik",
                "Ikot-Ekpene",
                "Ikot-Etefia",
                "Ikot-Ikpene",
                "Ikot-Mfon",
                "Ikot-Nya",
                "Ikot-Obong",
                "Ikot-Udobia",
                "Ikot-Udom",
                "Ikot-Udo-Ossom",
                "Ini",
                "Ini-Abasi",
                "Ini-Akpan",
                "Ini-Ekpe",
                "Ini-Idung",
                "Ini-Idung-Asanga",
                "Ini-Ita",
                "Ini-Mbang",
                "Ini-Udung",
                "Ini-Udom",
                "Ini-Udo-Ossom",
                "Inibehe",
                "Mbiabong",
                "Nko",
                "Nung-Idung",
                "Obot",
                "Ogbe-Utu",
                "Okat",
                "Oko",
                "Okon",
                "Okon-Ossom",
                "Okoro-Udofia",
                "Oku-Iboku",
                "Okuku",
                "Okutinyang",
                "Ona-Ito",
                "Oniong",
                "Udobia",
                "Udobia-Obom",
                "Udoma",
                "Udung",
                "Udung-Idung",
                "Udung-Uko",
                "Ukwok",
                "Ukwok-Afa",
                "Ukwok-Ita",
                "Ukwok-Ukata",
                "Utan",
                "Utit",
                "Utit-Uruan",
                "Uyo-Eti",
                "Uyo-Idung",
                "Uyo-Ita",
                "Uyo-Obot",
                "Uyo-Obo",
                "Uyo-Udung",
                "Uyo-Ukpa",
                "Uyo-Uruan",
            ],
            Itu: [
                "Afaha Oku",
                "Atai Obio Akpa",
                "Ata Obong",
                "Efa",
                "Ekim Enen",
                "Etim Ekpo",
                "Eton Obot",
                "Ikot Ebiere",
                "Ikot Edet",
                "Ikot Ekwere",
                "Ikot Essien",
                "Ikot Ibritam",
                "Ikot Itie Udung",
                "Ikot Ituen",
                "Ikot Ituen Inyang",
                "Ikot Nkanda",
                "Ikot Obot",
                "Ikot Okure",
                "Ikot Udom",
                "Ikot Udo Obobo",
                "Ikot Udo Ntuk",
                "Ikot Udo Ossom",
                "Ikot Ukap",
                "Ikot Umoessien",
                "Ikot Uso Okon",
                "Ini",
                "Ini Obot",
                "Ini-Abasi",
                "Ini-Ekpe",
                "Ini-Idung",
                "Ini-Idung-Asanga",
                "Ini-Ita",
                "Ini-Mbang",
                "Ini-Udung",
                "Ini-Udom",
                "Ini-Udo-Ossom",
                "Itam Uruan",
                "Itu Urban",
                "Mbokpu Ikot Ekong",
                "Mbiokporo Esa",
                "Mbioto",
                "Mbiuso",
                "Mbiuyo",
                "Ndiya",
                "Nduo Eduo",
                "Nduo Nkpene",
                "Nkari",
                "Nsit Atai",
                "Nung Akpan Essiet",
                "Nung Akpan Udosen",
                "Nung Anuak Ikot Oku Ubo",
                "Nung Asuquo",
                "Nung Atai",
                "Nung Eno",
                "Nung Etteh",
                "Nung Ibod Idim",
                "Nung Ikono Obio",
                "Nung Inyang",
                "Nung Iquok",
                "Nung Ita",
                "Nung Ita Ikot Ntuen",
                "Nung Ituen",
                "Nung Mbuk",
                "Nung Nkwe",
                "Nung Nya",
                "Nung Udoe",
                "Nung Udoe Idim",
                "Nung Udoe Udoma",
                "Nung Udoe Utit",
                "Nung Udoe Uyo",
                "Nung Udoekpo",
                "Nung Udoekpu",
                "Nung Udoma",
                "Nung Udoma Idua",
                "Nung Udo-Ossom",
                "Nung Udo-Ukam",
                "Nung Udo-Uruan",
                "Nung Udo-Utu",
                "Nung Udo-Utut",
                "Nung Udo-Utut Ukana",
                "Nung Udo-Utut Uruan",
                "Nung Udo-Utut-Atai",
                "Nung Udo-Utut-Oku",
                "Nung Udo-Utut-Uruan",
                "Nung Udo-Utut-Uyio",
                "Nung Udo-Utut-Uyo",
            ],
        },
    },
    {
        code: "AN",
        name: "Anambra",
        lgas: [
            "Aguata",
            "Anambra East",
            "Anambra West",
            "Anaocha",
            "Awka North",
            "Awka South",
            "Ayamelum",
            "Dunukofia",
            "Ekwusigo",
            "Idemili-North",
            "Idemili-South",
            "Ihiala",
            "Njikoka",
            "Nnewi-North",
            "Nnewi-South",
            "Ogbaru",
            "Onitsha-North",
            "Onitsha-South",
            "Orumba-North",
            "Orumba-South",
        ],
        subs: {},
    },
    {
        code: "BA",
        name: "Bauchi",
        lgas: [
            "Alkaleri",
            "Bauchi",
            "Bogoro",
            "Damban",
            "Darazo",
            "Dass",
            "Gamawa",
            "Ganjuwa",
            "Giade",
            "Itas Gadau",
            "Jama'Are",
            "Katagum",
            "Kirfi",
            "Misau",
            "Ningi",
            "Shira",
            "Tafawa-Balewa",
            "Toro",
            "Warji",
            "Zaki",
        ],
        subs: {},
    },
    {
        code: "BY",
        name: "Bayelsa",
        lgas: [
            "Brass",
            "Ekeremor",
            "Kolokuma Opokuma",
            "Nembe",
            "Ogbia",
            "Sagbama",
            "Southern-Ijaw",
            "Yenagoa",
        ],
        subs: {},
    },
    {
        code: "BE",
        name: "Benue",
        lgas: [
            "Ado",
            "Agatu",
            "Apa",
            "Buruku",
            "Gboko",
            "Guma",
            "Gwer-East",
            "Gwer-West",
            "Katsina-Ala",
            "Konshisha",
            "Kwande",
            "Logo",
            "Makurdi",
            "Ogbadibo",
            "Ohimini",
            "Oju",
            "Okpokwu",
            "Otukpo",
            "Tarka",
            "Ukum",
            "Ushongo",
            "Vandeikya",
        ],
        subs: {},
    },
    {
        code: "BO",
        name: "Borno",
        lgas: [
            "Abadam",
            "Askira-Uba",
            "Bama",
            "Bayo",
            "Biu",
            "Chibok",
            "Damboa",
            "Dikwa",
            "Gubio",
            "Guzamala",
            "Gwoza",
            "Hawul",
            "Jere",
            "Kaga",
            "Kala Balge",
            "Konduga",
            "Kukawa",
            "Kwaya-Kusar",
            "Mafa",
            "Magumeri",
            "Maiduguri",
            "Marte",
            "Mobbar",
            "Monguno",
            "Ngala",
            "Nganzai",
            "Shani",
        ],
        subs: {},
    },
    {
        code: "CR",
        name: "CrossRiver",
        lgas: [
            "Abi",
            "Akamkpa",
            "Akpabuyo",
            "Bakassi",
            "Bekwarra",
            "Biase",
            "Boki",
            "Calabar-Municipal",
            "Calabar-South",
            "Etung",
            "Ikom",
            "Obanliku",
            "Obubra",
            "Obudu",
            "Odukpani",
            "Ogoja",
            "Yakurr",
            "Yala",
        ],
        subs: {},
    },
    {
        code: "DE",
        name: "Delta",
        lgas: [
            "Aniocha North",
            "Aniocha-North",
            "Aniocha-South",
            "Bomadi",
            "Burutu",
            "Ethiope-East",
            "Ethiope-West",
            "Ika-North-East",
            "Ika-South",
            "Isoko-North",
            "Isoko-South",
            "Ndokwa-East",
            "Ndokwa-West",
            "Okpe",
            "Oshimili-North",
            "Oshimili-South",
            "Patani",
            "Sapele",
            "Udu",
            "Ughelli-North",
            "Ughelli-South",
            "Ukwuani",
            "Uvwie",
            "Warri South-West",
            "Warri North",
            "Warri South",
        ],
        subs: {},
    },
    {
        code: "EB",
        name: "Ebonyi",
        lgas: [
            "Abakaliki",
            "Afikpo-North",
            "Afikpo South (Edda)",
            "Ebonyi",
            "Ezza-North",
            "Ezza-South",
            "Ikwo",
            "Ishielu",
            "Ivo",
            "Izzi",
            "Ohaukwu",
            "Onicha",
        ],
        subs: {},
    },
    {
        code: "ED",
        name: "Edo",
        lgas: [
            "Akoko Edo",
            "Egor",
            "Esan-Central",
            "Esan-North-East",
            "Esan-South-East",
            "Esan-West",
            "Etsako-Central",
            "Etsako-East",
            "Etsako-West",
            "Igueben",
            "Ikpoba-Okha",
            "Oredo",
            "Orhionmwon",
            "Ovia-North-East",
            "Ovia-South-West",
            "Owan East",
            "Owan-West",
            "Uhunmwonde",
        ],
        subs: {},
    },
    {
        code: "EK",
        name: "Ekiti",
        lgas: [
            "Ado-Ekiti",
            "Efon",
            "Ekiti-East",
            "Ekiti-South-West",
            "Ekiti-West",
            "Emure",
            "Gbonyin",
            "Ido-Osi",
            "Ijero",
            "Ikere",
            "Ikole",
            "Ilejemeje",
            "Irepodun Ifelodun",
            "Ise-Orun",
            "Moba",
            "Oye",
        ],
        subs: {},
    },
    {
        code: "EN",
        name: "Enugu",
        lgas: [
            "Aninri",
            "Awgu",
            "Enugu-East",
            "Enugu-North",
            "Enugu-South",
            "Ezeagu",
            "Igbo-Etiti",
            "Igbo-Eze-North",
            "Igbo-Eze-South",
            "Isi-Uzo",
            "Nkanu-East",
            "Nkanu-West",
            "Nsukka",
            "Oji-River",
            "Udenu",
            "Udi",
            "Uzo-Uwani",
        ],
        subs: {},
    },
    {
        code: "GO",
        name: "Gombe",
        lgas: [
            "Akko",
            "Balanga",
            "Billiri",
            "Dukku",
            "Funakaye",
            "Gombe",
            "Kaltungo",
            "Kwami",
            "Nafada",
            "Shongom",
            "Yamaltu Deba",
        ],
        subs: {},
    },
    {
        code: "IM",
        name: "Imo",
        lgas: [
            "Aboh-Mbaise",
            "Ahiazu-Mbaise",
            "Ehime-Mbano",
            "Ezinihitte",
            "Ideato-North",
            "Ideato-South",
            "Ihitte Uboma",
            "Ikeduru",
            "Isiala-Mbano",
            "Isu",
            "Mbaitoli",
            "Ngor-Okpala",
            "Njaba",
            "Nkwerre",
            "Nwangele",
            "Obowo",
            "Oguta",
            "Ohaji-Egbema",
            "Okigwe",
            "Onuimo",
            "Orlu",
            "Orsu",
            "Oru-East",
            "Oru-West",
            "Owerri-Municipal",
            "Owerri-North",
            "Owerri-West",
        ],
        subs: {},
    },
    {
        code: "JI",
        name: "Jigawa",
        lgas: [
            "Auyo",
            "Babura",
            "Biriniwa",
            "Birnin-Kudu",
            "Buji",
            "Dutse",
            "Gagarawa",
            "Garki",
            "Gumel",
            "Guri",
            "Gwaram",
            "Gwiwa",
            "Hadejia",
            "Jahun",
            "Kafin-Hausa",
            "Kaugama",
            "Kazaure",
            "Kiri kasama",
            "Maigatari",
            "Malam Madori",
            "Miga",
            "Ringim",
            "Roni",
            "Sule-Tankarkar",
            "Taura",
            "Yankwashi",
        ],
        subs: {},
    },
    {
        code: "KD",
        name: "Kaduna",
        lgas: [
            "Birnin-Gwari",
            "Chikun",
            "Giwa",
            "Igabi",
            "Ikara",
            "Jaba",
            "Jema'A",
            "Kachia",
            "Kaduna-North",
            "Kaduna-South",
            "Kagarko",
            "Kajuru",
            "Kaura",
            "Kauru",
            "Kubau",
            "Kudan",
            "Lere",
            "Makarfi",
            "Sabon-Gari",
            "Sanga",
            "Soba",
            "Zangon-Kataf",
            "Zaria",
        ],
        subs: {},
    },
    {
        code: "KN",
        name: "Kano",
        lgas: [
            "Ajingi",
            "Albasu",
            "Bagwai",
            "Bebeji",
            "Bichi",
            "Bunkure",
            "Dala",
            "Dambatta",
            "Dawakin-Kudu",
            "Dawakin-Tofa",
            "Doguwa",
            "Fagge",
            "Gabasawa",
            "Garko",
            "Garun-Mallam",
            "Gaya",
            "Gezawa",
            "Gwale",
            "Gwarzo",
            "Kabo",
            "Kano-Municipal",
            "Karaye",
            "Kibiya",
            "Kiru",
            "Kumbotso",
            "Kunchi",
            "Kura",
            "Madobi",
            "Makoda",
            "Minjibir",
            "Nasarawa",
            "Rano",
            "Rimin-Gado",
            "Rogo",
            "Shanono",
            "Sumaila",
            "Takai",
            "Tarauni",
            "Tofa",
            "Tsanyawa",
            "Tudun-Wada",
            "Ungogo",
            "Warawa",
            "Wudil",
        ],
        subs: {},
    },
    {
        code: "KT",
        name: "Katsina",
        lgas: [
            "Bakori",
            "Batagarawa",
            "Batsari",
            "Baure",
            "Bindawa",
            "Charanchi",
            "Dan-Musa",
            "Dandume",
            "Danja",
            "Daura",
            "Dutsi",
            "Dutsin-Ma",
            "Faskari",
            "Funtua",
            "Ingawa",
            "Jibia",
            "Kafur",
            "Kaita",
            "Kankara",
            "Kankia",
            "Katsina",
            "Kurfi",
            "Kusada",
            "Mai-Adua",
            "Malumfashi",
            "Mani",
            "Mashi",
            "Matazu",
            "Musawa",
            "Rimi",
            "Sabuwa",
            "Safana",
            "Sandamu",
            "Zango",
        ],
        subs: {},
    },
    {
        code: "KE",
        name: "Kebbi",
        lgas: [
            "Aleiro",
            "Arewa-Dandi",
            "Argungu",
            "Augie",
            "Bagudo",
            "Birnin-Kebbi",
            "Bunza",
            "Dandi",
            "Fakai",
            "Gwandu",
            "Jega",
            "Kalgo",
            "Koko-Besse",
            "Maiyama",
            "Ngaski",
            "Sakaba",
            "Shanga",
            "Suru",
            "Wasagu/Danko",
            "Yauri",
            "Zuru",
        ],
        subs: {},
    },
    {
        code: "KO",
        name: "Kogi",
        lgas: [
            "Adavi",
            "Ajaokuta",
            "Ankpa",
            "Dekina",
            "Ibaji",
            "Idah",
            "Igalamela-Odolu",
            "Ijumu",
            "Kabba Bunu",
            "Kogi",
            "Lokoja",
            "Mopa-Muro",
            "Ofu",
            "Ogori Magongo",
            "Okehi",
            "Okene",
            "Olamaboro",
            "Omala",
            "Oyi",
            "Yagba-East",
            "Yagba-West",
        ],
        subs: {},
    },
    {
        code: "KW",
        name: "Kwara",
        lgas: [
            "Asa",
            "Baruten",
            "Edu",
            "Ekiti (Araromi/Opin)",
            "Ilorin-East",
            "Ilorin-South",
            "Ilorin-West",
            "Isin",
            "Kaiama",
            "Moro",
            "Offa",
            "Oke-Ero",
            "Oyun",
            "Pategi",
        ],
        subs: {},
    },
    {
        code: "LA",
        name: "Lagos",
        lgas: [
            "Agege",
            "Ajeromi-Ifelodun",
            "Alimosho",
            "Amuwo-Odofin",
            "Apapa",
            "Badagry",
            "Epe",
            "Eti-Osa",
            "Ibeju-Lekki",
            "Ifako-Ijaiye",
            "Ikeja",
            "Ikorodu",
            "Kosofe",
            "Lagos-Island",
            "Lagos-Mainland",
            "Mushin",
            "Ojo",
            "Oshodi-Isolo",
            "Shomolu",
            "Surulere",
            "Yewa-South",
        ],
        subs: {},
    },
    {
        code: "NA",
        name: "Nassarawa",
        lgas: [
            "Akwanga",
            "Awe",
            "Doma",
            "Karu",
            "Keana",
            "Keffi",
            "Kokona",
            "Lafia",
            "Nasarawa",
            "Nasarawa-Eggon",
            "Obi",
            "Wamba",
            "Toto",
        ],
        subs: {},
    },
    {
        code: "NI",
        name: "Niger",
        lgas: [
            "Agaie",
            "Agwara",
            "Bida",
            "Borgu",
            "Bosso",
            "Chanchaga",
            "Edati",
            "Gbako",
            "Gurara",
            "Katcha",
            "Kontagora",
            "Lapai",
            "Lavun",
            "Magama",
            "Mariga",
            "Mashegu",
            "Mokwa",
            "Moya",
            "Paikoro",
            "Rafi",
            "Rijau",
            "Shiroro",
            "Suleja",
            "Tafa",
            "Wushishi",
        ],
        subs: {},
    },
    {
        code: "OG",
        name: "Ogun",
        lgas: [
            "Abeokuta-North",
            "Abeokuta-South",
            "Ado-Odo Ota",
            "Ewekoro",
            "Ifo",
            "Ijebu-East",
            "Ijebu-North",
            "Ijebu-North-East",
            "Ijebu-Ode",
            "Ikenne",
            "Imeko-Afon",
            "Ipokia",
            "Obafemi-Owode",
            "Odeda",
            "Odogbolu",
            "Ogun-Waterside",
            "Remo-North",
            "Shagamu",
            "Yewa North",
        ],
        subs: {},
    },
    {
        code: "ON",
        name: "Ondo",
        lgas: [
            "Akoko North-East",
            "Akoko North-West",
            "Akoko South-West",
            "Akoko South-East",
            "Akure-North",
            "Akure-South",
            "Ese-Odo",
            "Idanre",
            "Ifedore",
            "Ilaje",
            "Ile-Oluji-Okeigbo",
            "Irele",
            "Odigbo",
            "Okitipupa",
            "Ondo West",
            "Ondo-East",
            "Ose",
            "Owo",
        ],
        subs: {},
    },
    {
        code: "OS",
        name: "Osun",
        lgas: [
            "Atakumosa West",
            "Atakumosa East",
            "Ayedaade",
            "Ayedire",
            "Boluwaduro",
            "Boripe",
            "Ede South",
            "Ede North",
            "Egbedore",
            "Ejigbo",
            "Ife North",
            "Ife South",
            "Ife-Central",
            "Ife-East",
            "Ifelodun",
            "Ila",
            "Ilesa-East",
            "Ilesa-West",
            "Irepodun",
            "Irewole",
            "Isokan",
            "Iwo",
            "Obokun",
            "Odo-Otin",
            "Ola Oluwa",
            "Olorunda",
            "Oriade",
            "Orolu",
            "Osogbo",
        ],
        subs: {},
    },
    {
        code: "OY",
        name: "Oyo",
        lgas: [
            "Afijio",
            "Akinyele",
            "Atiba",
            "Atisbo",
            "Egbeda",
            "Ibadan North",
            "Ibadan North-East",
            "Ibadan North-West",
            "Ibadan South-East",
            "Ibadan South-West",
            "Ibarapa-Central",
            "Ibarapa-East",
            "Ibarapa-North",
            "Ido",
            "Ifedayo",
            "Irepo",
            "Iseyin",
            "Itesiwaju",
            "Iwajowa",
            "Kajola",
            "Lagelu",
            "Ogo-Oluwa",
            "Ogbomosho-North",
            "Ogbomosho-South",
            "Olorunsogo",
            "Oluyole",
            "Ona-Ara",
            "Orelope",
            "Ori-Ire",
            "Oyo-West",
            "Oyo-East",
            "Saki-East",
            "Saki-West",
            "Surulere",
        ],
        subs: {},
    },
    {
        code: "PL",
        name: "Plateau",
        lgas: [
            "Barkin-Ladi",
            "Bassa",
            "Bokkos",
            "Jos-East",
            "Jos-North",
            "Jos-South",
            "Kanam",
            "Kanke",
            "Langtang-North",
            "Langtang-South",
            "Mangu",
            "Mikang",
            "Pankshin",
            "Qua'an Pan",
            "Riyom",
            "Shendam",
            "Wase",
        ],
        subs: {},
    },
    {
        code: "RI",
        name: "Rivers",
        lgas: [
            "Abua Odual",
            "Ahoada-East",
            "Ahoada-West",
            "Akuku Toru",
            "Andoni",
            "Asari-Toru",
            "Bonny",
            "Degema",
            "Eleme",
            "Emuoha",
            "Etche",
            "Gokana",
            "Ikwerre",
            "Khana",
            "Obio Akpor",
            "Ogba-Egbema-Ndoni",
            "Ogba Egbema Ndoni",
            "Ogu Bolo",
            "Okrika",
            "Omuma",
            "Opobo Nkoro",
            "Oyigbo",
            "Port-Harcourt",
            "Tai",
        ],
        subs: {},
    },
    {
        code: "SO",
        name: "Sokoto",
        lgas: [
            "Binji",
            "Bodinga",
            "Dange-Shuni",
            "Gada",
            "Goronyo",
            "Gudu",
            "Gwadabawa",
            "Illela",
            "Kebbe",
            "Kware",
            "Rabah",
            "Sabon Birni",
            "Shagari",
            "Silame",
            "Sokoto-North",
            "Sokoto-South",
            "Tambuwal",
            "Tangaza",
            "Tureta",
            "Wamako",
            "Wurno",
            "Yabo",
        ],
        subs: {},
    },
    {
        code: "TA",
        name: "Taraba",
        lgas: [
            "Ardo-Kola",
            "Bali",
            "Donga",
            "Gashaka",
            "Gassol",
            "Ibi",
            "Jalingo",
            "Karim-Lamido",
            "Kurmi",
            "Lau",
            "Sardauna",
            "Takum",
            "Ussa",
            "Wukari",
            "Yorro",
            "Zing",
        ],
        subs: {},
    },
    {
        code: "YO",
        name: "Yobe",
        lgas: [
            "Bade",
            "Bursari",
            "Damaturu",
            "Fika",
            "Fune",
            "Geidam",
            "Gujba",
            "Gulani",
            "Jakusko",
            "Karasuwa",
            "Machina",
            "Nangere",
            "Nguru",
            "Potiskum",
            "Tarmuwa",
            "Yunusari",
            "Yusufari",
        ],
        subs: {},
    },
    {
        code: "ZA",
        name: "Zamfara",
        lgas: [
            "Anka",
            "Bakura",
            "Birnin Magaji/Kiyaw",
            "Bukkuyum",
            "Bungudu",
            "Gummi",
            "Gusau",
            "Isa",
            "Kaura-Namoda",
            "Kiyawa",
            "Maradun",
            "Maru",
            "Shinkafi",
            "Talata-Mafara",
            "Tsafe",
            "Zurmi",
        ],
        subs: {},
    },
];
